import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  History,
  Search,
  CheckCircle2,
  Clock,
  Download,
  FileText,
  User,
  Sparkles,
  ChevronRight,
  ShieldCheck,
  RefreshCw,
  Database,
  Activity,
} from 'lucide-react';
import { Incident, AuditLogEntry } from '../types/index.js';
import { api } from '../services/api.js';
import { useDebounce } from '../hooks/useDebounce.js';

interface HistoryViewProps {
  incidents: Incident[];
  onSelectIncident: (incident: Incident) => void;
}

export const HistoryView: React.FC<HistoryViewProps> = ({ incidents, onSelectIncident }) => {
  const [activeTab, setActiveTab] = useState<'incidents' | 'audit'>('incidents');
  const [search, setSearch] = useState('');
  const debouncedSearch = useDebounce(search, 200);
  const [auditLogs, setAuditLogs] = useState<AuditLogEntry[]>([]);
  const [isLoadingAudit, setIsLoadingAudit] = useState(false);

  const fetchAuditLogs = useCallback(async () => {
    setIsLoadingAudit(true);
    try {
      const logs = await api.getAuditLogs(100);
      setAuditLogs(logs);
    } catch {
      // ignore
    } finally {
      setIsLoadingAudit(false);
    }
  }, []);

  useEffect(() => {
    if (activeTab === 'audit') {
      fetchAuditLogs();
    }
  }, [activeTab, fetchAuditLogs]);

  const resolvedIncidents = useMemo(() => {
    const term = debouncedSearch.toLowerCase().trim();
    return incidents.filter(
      (i) =>
        (i.status === 'RESOLVED' || i.status === 'CLOSED') &&
        (!term ||
          i.title.toLowerCase().includes(term) ||
          i.id.toLowerCase().includes(term) ||
          i.serviceName.toLowerCase().includes(term))
    );
  }, [incidents, debouncedSearch]);

  const filteredAuditLogs = useMemo(() => {
    const term = debouncedSearch.toLowerCase().trim();
    return auditLogs.filter(
      (log) =>
        !term ||
        log.action.toLowerCase().includes(term) ||
        log.userName.toLowerCase().includes(term) ||
        log.resourceType.toLowerCase().includes(term) ||
        log.details.toLowerCase().includes(term)
    );
  }, [auditLogs, debouncedSearch]);

  const calculateDurationMinutes = (created: string, resolved?: string) => {
    if (!resolved) return 30;
    const diff = (new Date(resolved).getTime() - new Date(created).getTime()) / (1000 * 60);
    return Math.max(1, Math.round(diff));
  };

  const handleExportPostmortem = (inc: Incident) => {
    const duration = calculateDurationMinutes(inc.createdAt, inc.resolvedAt);
    const md = `# SRE INCIDENT POST-MORTEM REPORT: ${inc.id}
**Title:** ${inc.title}
**Service:** ${inc.serviceName}
**Severity:** ${inc.severity}
**Status:** ${inc.status}
**Commander / Assignee:** ${inc.assignedEngineer?.name || 'Unassigned'} (${inc.assignedEngineer?.role || 'N/A'})

---
### Timelines
- **Declared:** ${new Date(inc.createdAt).toUTCString()}
- **Resolved:** ${inc.resolvedAt ? new Date(inc.resolvedAt).toUTCString() : 'N/A'}
- **Mean Time to Resolve (MTTR):** ${duration} minutes

---
### Incident Overview & Impact
${inc.description}

---
### Gemini AI Root Cause Analysis
**Diagnosis:**
${inc.aiAnalysis?.rootCauseSummary || inc.aiAnalysis?.probableRootCause || 'Root cause identified through log analysis.'}

**Blast Radius:**
${inc.aiAnalysis?.blastRadius || inc.aiAnalysis?.incidentSummary || 'Contained to target service.'}

**Failure Propagation Chain:**
${inc.aiAnalysis?.probableCauseChain?.map((s, i) => `${i + 1}. ${s}`).join('\n') || inc.aiAnalysis?.possibleAlternativeCauses?.map((s, i) => `${i + 1}. ${s}`).join('\n') || 'N/A'}

---
### Resolution Notes
${inc.resolutionNotes || 'Operational mitigation completed and verified by on-call engineer.'}

---
*Generated by AegisAI Reliability Platform on ${new Date().toISOString()}*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `POSTMORTEM-${inc.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div id="history-view" className="space-y-6">
      {/* Header with Navigation & Search */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-base font-semibold text-white flex items-center space-x-2">
            <History className="w-5 h-5 text-indigo-400" />
            <span>Incident Archive & Audit Trail</span>
          </h1>
          <p className="text-xs text-slate-400 mt-0.5">
            Database-backed post-mortems, MTTR records, and persistent compliance audit trail
          </p>
        </div>

        {/* Tab switcher */}
        <div className="flex items-center space-x-2 bg-slate-950 p-1 rounded-lg border border-slate-800">
          <button
            id="tab-history-incidents"
            onClick={() => setActiveTab('incidents')}
            className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all cursor-pointer ${
              activeTab === 'incidents'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Resolved Incidents ({resolvedIncidents.length})
          </button>
          <button
            id="tab-history-audit"
            onClick={() => setActiveTab('audit')}
            className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all cursor-pointer flex items-center space-x-1.5 ${
              activeTab === 'audit'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Database className="w-3.5 h-3.5 text-sky-400" />
            <span>Database Audit Logs</span>
          </button>
        </div>

        {/* Search */}
        <div className="relative w-full sm:w-64">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            id="search-history-input"
            type="text"
            placeholder={activeTab === 'incidents' ? 'Search resolved incidents...' : 'Search audit records...'}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-slate-800 border border-slate-700 rounded-lg pl-9 pr-3 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500"
          />
        </div>
      </div>

      {/* VIEW 1: RESOLVED INCIDENTS */}
      {activeTab === 'incidents' && (
        <div className="space-y-3">
          {resolvedIncidents.length === 0 ? (
            <div className="text-center py-12 bg-slate-900 border border-slate-800 rounded-xl">
              <History className="w-10 h-10 text-slate-600 mx-auto mb-2" />
              <p className="text-sm font-semibold text-slate-300">No Resolved Incidents in Archive</p>
              <p className="text-xs text-slate-400 mt-1">
                Active incidents will appear here once marked RESOLVED or CLOSED in the database.
              </p>
            </div>
          ) : (
            resolvedIncidents.map((inc) => {
              const mttr = calculateDurationMinutes(inc.createdAt, inc.resolvedAt);

              return (
                <div
                  key={inc.id}
                  id={`history-incident-${inc.id}`}
                  className="bg-slate-900 border border-slate-800 rounded-xl p-5 hover:border-slate-700 transition-all space-y-3"
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-mono text-xs font-bold text-emerald-400">{inc.id}</span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-bold">
                        {inc.status}
                      </span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                        {inc.severity}
                      </span>
                      <span className="text-xs font-semibold text-white">{inc.serviceName}</span>
                    </div>

                    <div className="flex items-center space-x-3 text-xs text-slate-400">
                      <div className="flex items-center space-x-1 font-mono">
                        <Clock className="w-3.5 h-3.5 text-emerald-400" />
                        <span>MTTR: <strong className="text-slate-200">{mttr} min</strong></span>
                      </div>
                      <span>•</span>
                      <span>Resolved {inc.resolvedAt ? new Date(inc.resolvedAt).toLocaleDateString() : 'N/A'}</span>
                    </div>
                  </div>

                  <div>
                    <h3 className="text-sm font-semibold text-white">{inc.title}</h3>
                    <p className="text-xs text-slate-300 mt-1 line-clamp-2 leading-relaxed font-sans">{inc.description}</p>
                  </div>

                  {/* AI Root Cause preview if present */}
                  {inc.aiAnalysis && (
                    <div className="bg-slate-950/60 border border-slate-800/80 rounded-lg p-3 text-xs space-y-1">
                      <div className="flex items-center space-x-1.5 text-indigo-400 font-semibold">
                        <Sparkles className="w-3.5 h-3.5" />
                        <span>Gemini AI Post-Mortem Diagnostic</span>
                        {inc.aiAnalysis.confidenceScore && (
                          <span className="text-[10px] font-mono px-1.5 rounded bg-indigo-500/20 text-indigo-300 ml-1">
                            {inc.aiAnalysis.confidenceScore}% confidence
                          </span>
                        )}
                      </div>
                      <p className="text-slate-300 line-clamp-2 leading-relaxed">
                        {inc.aiAnalysis.probableRootCause || inc.aiAnalysis.rootCauseSummary}
                      </p>
                    </div>
                  )}

                  {/* Resolution Notes preview */}
                  {inc.resolutionNotes && (
                    <div className="bg-emerald-950/20 border border-emerald-500/20 rounded-lg p-3 text-xs text-emerald-300/90">
                      <strong className="text-emerald-400 block mb-0.5">Resolution Notes:</strong>
                      <p className="line-clamp-2 leading-relaxed">{inc.resolutionNotes}</p>
                    </div>
                  )}

                  {/* Footer Controls */}
                  <div className="pt-2 border-t border-slate-800/80 flex items-center justify-between text-xs">
                    <div className="flex items-center space-x-2 text-slate-400">
                      <User className="w-3.5 h-3.5 text-slate-500" />
                      <span>Commander: <strong className="text-slate-300">{inc.assignedEngineer?.name || 'Unassigned'}</strong></span>
                    </div>

                    <div className="flex items-center space-x-2">
                      <button
                        id={`export-postmortem-${inc.id}`}
                        onClick={() => handleExportPostmortem(inc)}
                        className="flex items-center space-x-1.5 px-3 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 transition-colors cursor-pointer"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>Export Post-Mortem (.md)</span>
                      </button>

                      <button
                        id={`view-history-detail-${inc.id}`}
                        onClick={() => onSelectIncident(inc)}
                        className="text-indigo-400 hover:text-indigo-300 font-medium cursor-pointer"
                      >
                        Inspect &rarr;
                      </button>
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>
      )}

      {/* VIEW 2: DATABASE AUDIT TRAIL */}
      {activeTab === 'audit' && (
        <div className="space-y-3">
          <div className="flex items-center justify-between bg-slate-900 border border-slate-800 rounded-xl p-3">
            <div className="flex items-center space-x-2 text-xs text-slate-400">
              <Activity className="w-4 h-4 text-emerald-400" />
              <span>Immutable SQLite persistent audit logs for SOC2 compliance and platform auditing</span>
            </div>
            <button
              onClick={fetchAuditLogs}
              disabled={isLoadingAudit}
              className="flex items-center space-x-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-xs text-slate-200 transition-colors cursor-pointer"
            >
              <RefreshCw className={`w-3 h-3 ${isLoadingAudit ? 'animate-spin' : ''}`} />
              <span>Refresh Logs</span>
            </button>
          </div>

          {isLoadingAudit && auditLogs.length === 0 ? (
            <div className="text-center py-12 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-400">
              Loading persistent audit records...
            </div>
          ) : filteredAuditLogs.length === 0 ? (
            <div className="text-center py-12 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-400">
              No audit logs matching current filter.
            </div>
          ) : (
            <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-950/80 border-b border-slate-800 text-slate-400 font-mono text-[11px]">
                    <tr>
                      <th className="py-2.5 px-4">Timestamp (UTC)</th>
                      <th className="py-2.5 px-4">Actor</th>
                      <th className="py-2.5 px-4">Action</th>
                      <th className="py-2.5 px-4">Resource</th>
                      <th className="py-2.5 px-4">Event Details</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/60">
                    {filteredAuditLogs.map((log) => {
                      const getActionBadge = (act: string) => {
                        if (act.includes('LOGIN') || act.includes('SIGNUP')) return 'bg-emerald-500/20 text-emerald-400';
                        if (act.includes('CREATE')) return 'bg-indigo-500/20 text-indigo-400';
                        if (act.includes('AI')) return 'bg-purple-500/20 text-purple-400';
                        if (act.includes('RESOLVED')) return 'bg-emerald-500/20 text-emerald-400';
                        if (act.includes('UPDATED') || act.includes('CHANGE')) return 'bg-amber-500/20 text-amber-400';
                        return 'bg-slate-800 text-slate-300';
                      };

                      return (
                        <tr key={log.id} className="hover:bg-slate-800/40 transition-colors">
                          <td className="py-2.5 px-4 font-mono text-[11px] text-slate-400 whitespace-nowrap">
                            {new Date(log.createdAt).toLocaleString()}
                          </td>
                          <td className="py-2.5 px-4 whitespace-nowrap">
                            <div className="font-medium text-slate-200">{log.userName}</div>
                            <div className="text-[10px] text-slate-400 font-mono">{log.userRole}</div>
                          </td>
                          <td className="py-2.5 px-4 whitespace-nowrap">
                            <span className={`px-2 py-0.5 rounded text-[10px] font-bold font-mono ${getActionBadge(log.action)}`}>
                              {log.action}
                            </span>
                          </td>
                          <td className="py-2.5 px-4 whitespace-nowrap">
                            <span className="text-[10px] font-mono text-slate-400 bg-slate-950 px-1.5 py-0.5 rounded border border-slate-800">
                              {log.resourceType}
                            </span>
                          </td>
                          <td className="py-2.5 px-4 text-slate-300 max-w-md break-words font-sans">
                            {log.details}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
